# Generated by Django 5.2.16 on 2026-07-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='core_bookin_date_c6623d_idx',
            old_name='core_bookin_date_133b82_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='core_bookin_status_fe12a1_idx',
            old_name='core_bookin_status_672b05_idx',
        ),
    ]
